In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
embedding = nn.Embedding(10,3)
embedding.weight

Parameter containing:
tensor([[ 0.3297, -0.2363,  1.1949],
        [ 0.7753, -0.8578,  0.6417],
        [ 0.3704, -1.3876,  1.1840],
        [ 0.1575, -1.1846,  0.4829],
        [ 0.5767, -1.0877, -0.0936],
        [ 0.3862, -0.9740,  1.3367],
        [-0.6985, -0.1075,  0.2940],
        [-0.8649,  0.3607, -0.7779],
        [-0.2729, -1.3126,  2.0457],
        [ 1.4310, -1.2055,  0.2066]], requires_grad=True)

In [31]:

index = torch.tensor([1,2,4,7])
one_hot = F.one_hot(index, num_classes=10)
torch.mm(one_hot.to(torch.float32),embedding.weight.to(torch.float32))

tensor([[-1.0985, -1.3786,  1.0379],
        [-0.9161,  0.5010,  0.3951],
        [ 0.1891, -1.6724,  0.0869],
        [-1.8284,  0.4542,  0.6746]], grad_fn=<MmBackward0>)

In [8]:
##对非one-hot编码的embedding

embedding = nn.Embedding(5,3)

index = torch.tensor([[1,2,4,4],
                      [2,4,3,3]])

output = embedding(index)
output.shape

torch.Size([2, 4, 3])

In [7]:
text1 = "hello world"
text2 = "This is hello text"
#创建词汇表
vocab = set(text1.split()+text2.split())

embedding_dim = 5
embedding = nn.Embedding(len(vocab), embedding_dim)


# 将文本转换为索引序列
indices_1 = torch.tensor([list(vocab).index(word) for word in text1.split()])
indices_2 = torch.tensor([list(vocab).index(word) for word in text2.split()])

embedding_text1 = embedding(indices_1)
embedding_text2 = embedding(indices_2)

print(embedding_text1)
print(embedding_text2)

tensor([[ 0.7803,  0.4898,  0.5752, -0.1853, -0.7949],
        [-1.9149,  0.9856, -1.1941,  0.4726, -0.9358]],
       grad_fn=<EmbeddingBackward0>)
tensor([[-1.1205,  0.3835,  1.0347,  0.2198, -1.8546],
        [-0.4059, -0.7593,  0.1116,  2.7852,  0.2515],
        [ 0.7803,  0.4898,  0.5752, -0.1853, -0.7949],
        [-2.0266, -1.8509,  1.1672, -1.2701, -0.8621]],
       grad_fn=<EmbeddingBackward0>)


In [8]:
class student:
    def __init__(self,lastname) -> None:
        self.lastname = lastname
    @property
    def get(self):
        return self.lastname
    
    
a = student("xu")
a.get

'xu'