In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
embedding = nn.Embedding(10,3)
embedding.weight

Parameter containing:
tensor([[-0.2286,  1.0366,  0.3008],
        [-0.4114,  0.7324, -2.0017],
        [ 1.4847,  0.6844,  0.3838],
        [ 0.8960,  0.1266, -1.2354],
        [-0.6514, -0.6721, -0.1284],
        [ 1.4808, -0.5307,  1.2425],
        [-0.1112, -0.2260,  0.8036],
        [-1.6207, -0.4328,  0.4073],
        [ 0.9712,  1.2995,  0.5779],
        [ 0.1531, -2.2072,  0.3059]], requires_grad=True)

In [31]:

index = torch.tensor([1,2,4,7])
one_hot = F.one_hot(index, num_classes=10)
torch.mm(one_hot.to(torch.float32),embedding.weight.to(torch.float32))

tensor([[-1.0985, -1.3786,  1.0379],
        [-0.9161,  0.5010,  0.3951],
        [ 0.1891, -1.6724,  0.0869],
        [-1.8284,  0.4542,  0.6746]], grad_fn=<MmBackward0>)

In [32]:
embedding(index)

tensor([[-1.0985, -1.3786,  1.0379],
        [-0.9161,  0.5010,  0.3951],
        [ 0.1891, -1.6724,  0.0869],
        [-1.8284,  0.4542,  0.6746]], grad_fn=<EmbeddingBackward0>)

In [7]:
text1 = "hello world"
text2 = "This is hello text"
#创建词汇表
vocab = set(text1.split()+text2.split())

embedding_dim = 5
embedding = nn.Embedding(len(vocab), embedding_dim)


# 将文本转换为索引序列
indices_1 = torch.tensor([list(vocab).index(word) for word in text1.split()])
indices_2 = torch.tensor([list(vocab).index(word) for word in text2.split()])

embedding_text1 = embedding(indices_1)
embedding_text2 = embedding(indices_2)

print(embedding_text1)
print(embedding_text2)

tensor([[ 0.7803,  0.4898,  0.5752, -0.1853, -0.7949],
        [-1.9149,  0.9856, -1.1941,  0.4726, -0.9358]],
       grad_fn=<EmbeddingBackward0>)
tensor([[-1.1205,  0.3835,  1.0347,  0.2198, -1.8546],
        [-0.4059, -0.7593,  0.1116,  2.7852,  0.2515],
        [ 0.7803,  0.4898,  0.5752, -0.1853, -0.7949],
        [-2.0266, -1.8509,  1.1672, -1.2701, -0.8621]],
       grad_fn=<EmbeddingBackward0>)


In [8]:
class student:
    def __init__(self,lastname) -> None:
        self.lastname = lastname
    @property
    def get(self):
        return self.lastname
    
    
a = student("xu")
a.get

'xu'