包torch包含了多维张量的数据结构以及基于其上的多种数学操作。

In [2]:
import torch
a = torch.randn(1,2,3,4,5)
a.numel()
torch.no_grad() #不计算梯度

120

<font face="黑体" color=white font size=5>创建操作

In [3]:
num = 10
torch.eye(num) #返回对角线为1的矩阵

start = 1
end = 0
torch.linspace(start, end, steps=10, out=None) #间隔均匀的取steps个点产生一维张量
torch.logspace(start, end, steps=10, out=None) #在10^start到10^end之间取steps个点


size = [2,3]
torch.rand(size)      #从0，1均匀分布中随机采样
torch.randn(size)     ##从0均值，1方差中随机采样

torch.arange(1,2.5,0.5)  #从1到2.5以0.5为步长的tensor序列 range类似，但是建议使用arange

tensor([1.0000, 1.5000, 2.0000])

<font face="黑体" color=white font size=5> 索引,切片,连接,换位操作

In [4]:
#对给定维度的张量序列进行连接操作,是chunk和split的反操作
x = torch.randn(4,3)
y = torch.cat([x,x,x],dim=0)
y.shape

#在dim维度上将input均匀分成chunks份
torch.chunk(input=x, chunks=2, dim=0) 

##在dim上按照split_size进行划分，不能均分的话最后一个会小于其他块
x = torch.rand([3,4,5])
torch.split(x,2,dim=2)

#沿给定轴dim，将输入索引张量index指定位置的值进行聚合。
# out[i][j][k] = tensor[index[i][j][k]][j][k]  # dim=0
# out[i][j][k] = tensor[i][index[i][j][k]][k]  # dim=1
# out[i][j][k] = tensor[i][j][index[i][j][k]]  # dim=2
#可以理解成将input的dim维度按照index进行重新排序
t = torch.Tensor([[1,2],[3,4]])
print(t)
torch.gather(input=t, dim=1, index=torch.LongTensor([[0,0],[1,0]]))

##返回非零元素索引
torch.nonzero(torch.Tensor([1, 1, 1, 0, 1]))

#压缩去除形状中的1部分,可以指定维度
x = torch.squeeze(torch.rand([1,1,10]),dim=1)
x.shape
#与squeeze相反
torch.unsqueeze(x,dim=-1).shape

#沿着一个新维度进行连接 3*[1,2] -> [3,1,2]
x = torch.rand(1,2)
torch.stack([x,x,x],dim=0).shape

#交换dim0与dim1的维度
x = torch.transpose(x,0,1)
x.shape

#返回一个新的原始tensor的视图
x = torch.randn(3,4,5)
x.permute((2,0,1)).size()

#重塑形状，通常是一个视图
torch.reshape(x, (10,-1)).size()


tensor([[1., 2.],
        [3., 4.]])


torch.Size([10, 6])

<font face="黑体" color=white font size=5> 随机采样

In [22]:
#输入每个位置为1的概率，输出采样结果
a = torch.empty(3,3).uniform_(0,1)
torch.bernoulli(a)

#input为取到的概率,在多项式分布中采样任意个点,replacement表示是否可重复
weights = torch.tensor([0, 10, 3, 0], dtype=torch.float) # create a tensor of weights
torch.multinomial(weights, 4, replacement=True)

#输入mean与std实现从正态分布中采样
#可以选择形状
torch.normal(0,1,size=[2,3])
torch.normal(mean=0, std=torch.arange(0,1,0.1))


tensor([ 0.0000, -0.2185, -0.0511,  0.5179,  0.4653, -0.5264, -0.3094,  1.0748,
         0.6943, -0.9734])

<font face="黑体" color=white font size=5> 序列化(保存与读取)

In [ ]:
#保存一个对象
import torchvision
import io
torch.save()
model_vgg = torchvision.models.vgg16()

#保存模型
torch.save(model_vgg.state_dict(),"vgg16_method2.pth") ##只有参数

#加载模型
model2_vgg = torchvision.models.vgg16()         
model2_vgg.load_state_dict(torch.load("vgg16_method2.pth"),strict=False)  ##再回复参数

#保存数据
x = torch.rand(1,2)
buffer = io.BytesIO()
torch.save(x, buffer)

#读取一个对象,map_loaction可以对数据进行重映射
torch.load("x.pt",map_location='cpu')



<font face="黑体" color=white font size=5> 数学操作

In [27]:
#按位操作
torch.asin() #反正弦 arcsin
torch.atan() #反正切 arctan
torch.ceil() #对每个元素向上取整
torch.clamp()  #将每个元素收缩到min,max区间，原本在区间的不变，大的变为max，小的变为min
input = torch.rand([2,3])
value = 2
torch.div(input, value) #逐元素除法
torch.mul(input,value) #逐元素乘法
torch.reciprocal(input) #逐个元素取倒数
torch.round(value) #逐元素舍入到最近的整数
torch.sign(value) #返回一个元素的正负


TypeError: asin() missing 1 required positional arguments: "input"

<font face="黑体" color=white font size=5> Reduction Ops

In [49]:

#Reduciton Ops

input = torch.randn([3,4])
print(input)
torch.argmax(input,dim=0)  #返回dim中最大值的索引
torch.argmin(input,dim=0) #返回最小值索引
torch.amax(input,dim=0)  #返回最大值 amin返回最小值
input[1][1] = False
torch.all(input,dim=1)  ##每个都是True返回True
torch.any(input)  ## 任意一个是True返回True

other = torch.randn([3,4])
torch.dist(input, other, 1) #返回两个张量之间的p距离
torch.mean(input)  ##返回均值
torch.std(input) #返回标准差
torch.var(input) #返回方差
torch.norm(input,1) #返回张量的p范数
torch.prod(input) #返回所有元素的积，或者给定维度上的乘积

#Comparision Ops
torch.eq(input, other)
torch.isnan(input)
torch.le(input, other) #小于等于
torch.sort(input,dim=1) #排序


# other Ops

torch.diag(input,diagonal=0) #input为1D返回2D对角矩阵，2D则返回1D对角元素
torch.trace(input)  ##计算迹

#矩阵复制
torch.clone(input)
input.detach()

#矩阵乘法
torch.mm(input,other.T).size()
torch.randn([10,3,4])
torch.bmm(torch.randn([10,3,4]), torch.randn([10,4,5])).size() #批处理的矩阵乘法，第一维会被当做batchsize
torch.diff(input) #计算相邻元素的差值




tensor([[-0.7188, -1.5850,  0.6654, -0.4265],
        [-0.0067,  0.4627,  2.3477, -1.6450],
        [-0.9745,  2.2250,  0.6201, -0.6038]])


torch.Size([10, 3, 5])